services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - smarttj-network

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped

    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD-SHELL", 'redis-cli -a "$$REDIS_PASSWORD" ping']
      interval: 10s
      timeout: 5s
      retries: 5

    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "${REDIS_PASSWORD}",
      ]

    networks:
      - smarttj-network

  grafana:
    image: grafana/grafana:13.2.3
    container_name: grafana
    restart: unless-stopped

    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=${GRAFANA_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true

volumes:
  postgres_data:
  redis-data:

networks:
  smarttj-network:
    external: true
